export const MOVIE_URL = 'http://localhost:8383/api/movie'
export const CREW_URL = 'http://localhost:8383/api/crew'
export const IMAGE_URL = 'http://localhost:8383/api/image'
export const CINEMA_URL = 'http://localhost:8383/api/cinema'
export const THEATER_URL = 'http://localhost:8383/api/theater'